### ISSUE TITLE
Adding Radio select field results in error

### ISSUE THREAD

**Issue by jkoninger** [octavenz/wagtail-advanced-form-builder#8]
Adding a radio select field results in the following error

```
Traceback (most recent call last):
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail\views.py", line 28, in serve
    return page.serve(request, *args, **kwargs)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail_advanced_form_builder\models\abstract_advanced_form_mixin.py", line 369, in serve
    form = self.get_form(page=self, user=request.user)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail_advanced_form_builder\models\abstract_advanced_form_mixin.py", line 272, in get_form
    form = super().get_form(*args, **kwargs)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail\contrib\forms\models.py", line 196, in get_form
    form_class = self.get_form_class()
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail\contrib\forms\models.py", line 190, in get_form_class
    return fb.get_form_class()
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail\contrib\forms\forms.py", line 162, in get_form_class
    return type(str("WagtailForm"), (BaseForm,), self.formfields)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail\contrib\forms\forms.py", line 146, in formfields
    formfields[clean_name] = create_field(field, options)
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail_advanced_form_builder\forms\advanced_form_builder.py", line 75, in create_radio_field
    options['choices'] = list(map(
  File "C:\Users\jahan\anaconda3\envs\wagtail\lib\site-packages\wagtail_advanced_form_builder\forms\advanced_form_builder.py", line 76, in &lt;lambda&gt;
    lambda x: (x.strip(), x.strip()),

Exception Type: AttributeError
Exception Value: 'dict' object has no attribute 'strip'
```

I am using Django 4.0.5 and Python 3.9.12.

Thanks in advance :)

**Comment by jkoninger** [comment]
Just realised that this is the same issue as mentioned in #5 so this is clearly not isolated to radio fields

**Comment by UDAR-TomH** [comment]
This remains broken. Any ETA on a fix?

**Comment by andreobriennz** [comment]
@UDAR-TomH  I think it's been fixed with this PR https://github.com/octavenz/wagtail-advanced-form-builder/pull/12
